# Generated by Django 4.1.5 on 2023-01-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
