# Generated by Django 4.1.5 on 2023-01-19 16:27

import applications.payments.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_key', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50, verbose_name=(('month', 'Month'), ('year', 'Year')))),
                ('discount', models.PositiveIntegerField(default=20)),
                ('final_price', models.PositiveIntegerField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='section.section')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('card_type', models.CharField(max_length=180, verbose_name=(('visa', 'Visa'), ('elcart', 'Elcart'), ('mastercard', 'MasterCard'), ('unionpay', 'UnionPay'), ('american_express', 'American Express')))),
                ('card_number', models.CharField(max_length=19, validators=[applications.payments.validators.CCNumberValidator()])),
                ('card_expiry_date', models.DateField(verbose_name="['%m/%y', '%m/%Y']")),
                ('card_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
