# Generated by Django 4.1.5 on 2023-01-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expiration_date',
        ),
    ]
