# Generated by Django 4.1.5 on 2023-01-25 07:01

import applications.payments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_number',
            field=models.CharField(max_length=19, unique=True, validators=[applications.payments.validators.CCNumberValidator()]),
        ),
    ]
