# Generated by Django 4.1.5 on 2023-01-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
