# Generated by Django 4.1.4 on 2023-01-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poster/')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
